name: "Tests"

on:
  push:
  schedule:
  - cron: "0 3 * * 5"
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: zini

      - uses: mlugg/setup-zig@v2

      - name: Formatting
        run: zig fmt --check src/*.zig
        working-directory: zini

      - name: Tests
        run: zig build test
        working-directory: zini

      - name: Build executables
        run: zig build
        working-directory: zini
